- name: Validate required variables
  ansible.builtin.assert:
    that:
      - wazuh_agent_manager_host | length > 0
    fail_msg: "wazuh_agent_manager_host must be defined."

- name: Install wazuh agent
  ansible.builtin.include_tasks: install.yml

- name: Configure wazuh agent
  ansible.builtin.include_tasks: configure.yml

- name: Register wazuh agent
  ansible.builtin.include_tasks: register.yml
  when: wazuh_agent_auto_register | bool